README.md
data/AMI_CV.R
data/Mechanical_Turk_Lexical.R

Added data for https://github.com/ben-domingue/irw/issues/60 and https://github.com/ben-domingue/irw/issues/114
Fixed the link to to-be-processed data-queue to Issue in README.md. The old one leads to the void :|

AMI_CV.R | Mechanical_Turk_Lexical.R | README.md

---

data/DART_Brysbaert_2020.R
data/GART_Grolig_2020.R

Code for this issue: https://github.com/ben-domingue/irw/issues/134

DART_Brysbaert_2020 | GART_Grolig_2020

---

data/GERAS_Gruber_2019.R

Issue for this PR: https://github.com/ben-domingue/irw/issues/199

GERAS_Gruber_2019.R

---

data/HEARD_Roch_2022.R
data/WMD_Bartczuk_2023.R

PR for this issue: https://github.com/ben-domingue/irw/issues/334
PR for this issue: https://github.com/ben-domingue/irw/issues/335

WMD_Bartczuk_2023.R | HEARD_Roch_2022.R

---

data/LSHS-E_Quidaja_2022.R
data/SAS_Deters_2022.R

PR for this issue: https://github.com/ben-domingue/irw/issues/366
PR for this issue: https://github.com/ben-domingue/irw/issues/360

LSHS-E_Quidaja_2022.R ｜ SAS_Deters_2022.R

---

data/Aspirations_Sonmez_2022.R
data/dumas_Organisciak_2022.R

PR for this issue: https://github.com/ben-domingue/irw/issues/344

Aspirations_Sonmez_2022.R | dumas_Organisciak_2022

---

data/CBI_Rodriguez_2021.R

PR for this issue: https://github.com/ben-domingue/irw/issues/407

CBI_Rodriguez_2021.R

---

data/PTCI_Chinese_Zhan_2024.R

PR for this issue: https://github.com/ben-domingue/irw/issues/403

PTCI_Chinese_Zhan_2024.R

---

data/CVE-PHQ8_Carter_2024.R
data/PMT_Trzcińska_2023.R

PR for this issue: https://github.com/ben-domingue/irw/issues/463
PR for this issue: https://github.com/ben-domingue/irw/issues/460

CVE-PHQ8_Carter_2024.R | PMT_Trzcinska_2023.R

---

data/PTAM_Kretzschmar_2017.R

PR for this issue: https://github.com/ben-domingue/irw/issues/458

PTAM_Kretzschmar_2017.R

---

data/FEDSP_Trzcińska_2024.R

PR for this issue: https://github.com/ben-domingue/irw/issues/466

FEDSP_Trzcinska_2024

---

data/CPDMMC_Kunnari_2020.R

PR for this issue: https://github.com/ben-domingue/irw/issues/456

CPDMMC_Kunnari_2020.R 

---

data/VEI_Brazillian_Shiramizu_2018.R

PR for issue: https://github.com/ben-domingue/irw/issues/574

VEI_Brazillian_Shiramizu_2018.R

---

data/PSR-P_Scale_Intimacy_Hakim_2018.R
data/SV-MAIA2_Randelovic_2021.R
data/SV-MAIA2_Ranđelović_2021.R

PR for issue:https://github.com/ben-domingue/irw/issues/578

SV-MAIA2_Ranđelović_2021.R | PSR-P_Scale_Intimacy_Hakim_2018.R

---

data/FACES_Spanish_Vegas_2022.R

PR for this issue:https://github.com/ben-domingue/irw/issues/547

Added FACES_Spanish_Vegas_2022.R

---

data/NAMPRB_Siwiak_2024.R

PR for this issue: https://github.com/ben-domingue/irw/issues/319

NAMPRB_Siwiak_2024.R

---

data/SABFI2_Gallardo_Pujol_2018.R

PR for this issue: https://github.com/ben-domingue/irw/issues/433

SABFI2_Gallardo_Pujol_2018.R

---

data/RD_EppSCQRK_Kipkemoi_2024.R
data/RD_PpCvDOS_PadcOnaCns_Jinbo_2019.R

PR for this issue: https://github.com/ben-domingue/irw/issues/514

RD_PpCvDOS_PadcOnaCns_Jinbo_2019.R | RD_EppSCQRK_Kipkemoi_2024.R

---

data/PPCDRSSA_FranciscoJ_2023.R

PR for this issue: https://github.com/ben-domingue/irw/issues/312

PPCDRSSA_FranciscoJ_2023.R

---

data/PPPSSAPIS_Figlova_2021.R

PR for this issue: https://github.com/ben-domingue/irw/issues/602

PPPSSAPIS_Figlova_2021.R

---

data/PeSCBCSCe_Novak_2020.R

PR for issue: https://github.com/ben-domingue/irw/issues/245

PeSCBCSCe_Novak_2020.R

---

data/APFCompact_Ptacek_2024_AAQII.do
data/APFCompact_Ptacek_2024_DASS21.do
data/APFCompact_Ptacek_2024_SWLS.do
data/PROMISPME_Forrest_2021.R

PR for issue: https://github.com/ben-domingue/irw/issues/527

PROMISPME_Forrest_2021.R

---

data/PROMISPFUE_2.0E_Gershon_2019.R

PR for issue: https://github.com/ben-domingue/irw/issues/525

PROMISPFUE_2.0E_Gershon_2019.R

---

data/CV_OASIS_ODSIS_PPE_Novak_2020.R

PR for this issue: https://github.com/ben-domingue/irw/issues/441#event-14904629741
Still need to add data dict rows/permission from author

CV_OASIS_ODSIS_PPE_Novak_2020.R

---

data/CQTMS_Hur_2023.R
data/CSE_Bayazit_2022.R

PR for this issue:https://github.com/ben-domingue/irw/issues/629
PR for this issue: https://github.com/ben-domingue/irw/issues/631

CQTMS_Hur_2023.R | CSE_Bayazit_2022.R

---

data/QaSLU_Prado_2024.R

PR for this issue:https://github.com/ben-domingue/irw/issues/632

QaSLU_Prado_2024.R

---

data/EEN_Lacey_2024.R

PR for this issue: https://github.com/ben-domingue/irw/issues/580

EEN_Lacey_2024.R

---

data/QCDQES_Oliveira_2022.R

PR for issue: https://github.com/ben-domingue/irw/issues/438

QCDQES_Oliveira_2022.R

---

data/PEPABAS2C_Kubicka_2024.r

PR for this issue: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=86062786&issue=ben-domingue%7Cirw%7C510

Added PEPABAS2C_Kubicka_2024.r

---

data/VSOCFP_Sebo_2024.R

For this issue: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=86097309&issue=ben-domingue%7Cirw%7C444

VSOCFP_Sebo_2024.R

---

data/SPQVS_Barnby_2017.R

PR for issue: https://github.com/ben-domingue/irw/issues/427

SPQVS_Barnby_2017.R

---

data/SBD_Smith_2020.r

PR for issue: https://github.com/ben-domingue/irw/issues/459

SBD_Smith_2020.r

---

data/PPSRS_Caliciuri_2024.r

PR for issue: https://github.com/ben-domingue/irw/issues/400

PPSRS_Caliciuri_2024.r

---

data/MMF_Solis_2020.r

Code for issue: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=88136393&issue=ben-domingue%7Cirw%7C599.
QCed by Ben

MMF_Solis_2020

---

data/SCS_Suh_2023.r

PR for issue: https://github.com/ben-domingue/irw/issues/398

SCS_Suh_2023.r

---

data/CHEXI_Lin_2019.r

PR for issue: https://github.com/ben-domingue/irw/issues/518

CHEXI_Lin_2019.r

---

data/Ellipse_Corssley_2024.r

PR for issue: https://github.com/ben-domingue/irw/issues/655

Ellipse_Corssley_2024.r

---

data/MGSISGCLQ_Hollyhead_2018.r

PR for issue: https://github.com/ben-domingue/irw/issues/442

MGSISGCLQ_Hollyhead_2018.r

---

data/mbft_anunciacao_2024.r

PR for issue: https://github.com/ben-domingue/irw/issues/740

mbft_anunciacao_2024.r

---

data/iewsriting_molloy_2022.r

PR for issue: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=90869540&issue=ben-domingue%7Cirw%7C739

iewsriting_molloy_2022.r

---

data/ECPS_Sahm_2024.r

PR for issue: https://github.com/ben-domingue/irw/issues/436

ECPS_Sahm_2024.r

---

data/aappss_malpas_2019_scl.r

PR for https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=94258210&issue=ben-domingue%7Cirw%7C495

Added aappss_malpas_2019_scl.r

---

data/fcupanas_cffsdas_reyna_2018.r

PR for https://github.com/ben-domingue/irw/issues/308

fcupanas_cffsdas_reyna_2018.r

---

data/ml_harper_2016.r

PR for issue: https://github.com/ben-domingue/irw/issues/781#issuecomment-2616615861

ml_harper_2016.r

---

data/dvivdtws_ppmial_marcatto_2023.r

PR for issue: https://github.com/ben-domingue/irw/issues/375

dvivdtws_ppmial_marcatto_2023.r

---

data/ThreatPerceptions_Isler_2024.R

updated "experiment" to "treat"

ThreatPerceptions_Isler_2024 updated

---

data/det_naismith_2023.r

PR for issue: https://github.com/ben-domingue/irw/issues/738#issuecomment-2616618534

det_naismith_2023.r

---

data/ml_harper_2015.r

PR for: https://github.com/ben-domingue/irw/issues/781#issuecomment-2631761359

ml_harper_2015.r

---

data/erf_breuer_2017.r

PR for https://github.com/ben-domingue/irw/issues/435
[erf_breuer_2017.zip](https://github.com/user-attachments/files/18550025/erf_breuer_2017.zip)

erf_breuer_2017.r

---

data/rvobgvmaas_lsf_lehing_2024.r

PR for: https://github.com/ben-domingue/irw/issues/799#issuecomment-2635455241

rvobgvmaas_lsf_lehing_2024.r

---

data/ccapsvtskhpacr_mercedes_2023.r
data/ftna_kasper_2022.r

PR for: https://github.com/ben-domingue/irw/issues/761#issuecomment-2602516476

ftna_kasper_2022.r

---

irw-dataset-builder/main.py

Add new features to fix issues #804, #805, #806

---

data/imos_2018.r

PR for issue: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=90555579&issue=ben-domingue%7Cirw%7C729

imos_2018.r

---

data/evpromisi_stone_2021.r

PR for issue: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=97013757&issue=ben-domingue%7Cirw%7C549

evpromisi_stone_2021.r

---

data/paampsmartsud_saba_2023.r

PR for issue: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=99216005&issue=ben-domingue%7Cirw%7C358

paampsmartsud_saba_2023.r

---

data/brand_brand_raffaelli_2024.r

PR for: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=97597611&issue=ben-domingue%7Cirw%7C827

brand_brand_raffaelli_2024.r

---

data/mhscdc_fried_2020.r

PR for issue: https://github.com/ben-domingue/irw/issues/873

mhscdc_fried_2020.r

---

data/oxfordcovid_xue_2024.r

PR for issue: https://github.com/ben-domingue/irw/issues/862

oxfordcovid_xue_2024.r

---

data/rrca_mcneish_2025.r

PR for: https://github.com/ben-domingue/irw/issues/841

rrca_mcneish_2025.r

---

data/gpt4mcq_young_2025.r

Data for: https://github.com/ben-domingue/irw/issues/809

gpt4mcq_young_2025.r

---

data/csft_ye_2025.r

PR for https://github.com/ben-domingue/irw/issues/914#issuecomment-2755056548

csft_ye_2025.r

---

data/hexaco_ashton_2014.r

PR for https://github.com/ben-domingue/irw/issues/895#issuecomment-2784068276

hexaco_ashton_2014.r

---

data/bfi_goldberg_1992.r

PR for https://github.com/ben-domingue/irw/issues/900

bfi_goldberg_1992.r

---

data/ipip_openpsychometrics.r

PR for issue: https://github.com/ben-domingue/irw/issues/896#issuecomment-2853125334

ipip_openpsychometrics

---

data/qol_islam_2025.r

PR for https://github.com/ben-domingue/irw/issues/797

Added qol_islam_2025.r

---

data/idcr_martinez_2023.r

PR for issue: https://github.com/ben-domingue/irw/issues/659

idcr_martinez_2023.r

---

data/parc_balaji_2017.r

PR for issue: https://github.com/ben-domingue/irw/issues/981

parc_balaji_2017.r

---

data/bmeess_innamorati_2019.r

PR for: https://github.com/users/ben-domingue/projects/1/views/3?pane=issue&itemId=91631176&issue=ben-domingue%7Cirw%7C249

Added bmeess_innamorati_2019.r
